name: bio-core-torch
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec
  - conda-build
  - h5py >=2.10,<2.11
  - mypy
  - pip
  - pytest
  - python >=3.7
  - xarray
  - pytorch <1.10
  - onnxruntime
  - tifffile
