name: Test and Deploy bioimageio.core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  test-base-bioimage-spec-conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-core-dev
        environment-file: dev/environment-base.yaml
        python-version: ${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: conda develop .
    - name: pytest-base-bioimage-spec-conda
      shell: bash -l {0}
      run: pytest

  test-base-bioimage-spec-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-core-dev
        environment-file: dev/environment-base.yaml
        python-version: ${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --force bioimageio.spec
        conda install -c pytorch -c conda-forge -y pip
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        conda develop .
    - name: pytest-base-bioimage-spec-main
      shell: bash -l {0}
      run: pytest

  conda-build:
    runs-on: ubuntu-latest
    needs: test-base-bioimage-spec-conda
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
    - name: linux conda build
      shell: bash -l {0}
      run: |
        conda install -n base -c conda-forge conda-build pip -y
        conda build -c conda-forge conda-recipe
